public class Ejercicio4 {
    public static void main(String[] args) {
        System.out.println("┌───────────┬─────────────┬──────────────┬───────────────┬────────────┬─────────────┬────────────┬─────────────┐");
        System.out.println("│    HORA   │    LUNES    │    MARTES    │   MIERCOLES   │   JUEVES   │   VIERNES   │   SABADO   │   DOMINGO   │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │   calculo 1  │               │            │             │            │             │");
        System.out.println("│06:20-7:10 │             │   Franklin   │               │            │             │            │             │");
        System.out.println("│           │             │  Aula L-602  │               │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │   calculo 1  │               │            │             │            │             │");
        System.out.println("│07:10-8:00 │             │   Franklin   │               │            │             │            │             │");
        System.out.println("│           │             │  Aula L-602  │               │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │ ALGO. Y PRO.│INVES. DE OPE.│  ESTADISTICA  │ ESTADISTICA│             │            │             │");
        System.out.println("│08:00-8:50 │   EDUARDO   │    YULIANA   │    TORIBIO    │  TORIBIO   │             │            │             │");
        System.out.println("│           │ AULA L-501  │  AULA L-601  │   AULA L-501  │ AULA L-501 │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │ ALGO. Y PRO.│INVES. DE OPE.│  ESTADISTICA  │ ESTADISTICA│             │            │             │");
        System.out.println("│08:50-9:40 │   EDUARDO   │   YULIANA    │    TORIBIO    │  TORIBIO   │             │            │             │");
        System.out.println("│           │ AULA L-501  │  AULA L-601  │   AULA L-501  │ AULA L-501 │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │ ALGO. Y PRO.│INVES. DE OPE.│ ING. DE SIS.  │INVES. DE O.│             │            │             │");
        System.out.println("│09:40-10:30│   EDUARDO   │   YULIANA    │   YULIANA     │  YULIANA   │             │            │             │");
        System.out.println("│           │ AULA L-501  │  AULA L-601  │  AULA L-509   │ AULA L-509 │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │ ING. DE SIS.│              │ ING. DE SIS.  │INVES. DE O.│             │            │             │");
        System.out.println("│10:30-11:20│   YULIANA   │              │   YULIANA     │  YULIANA   │             │            │             │");
        System.out.println("│           │ AULA L-509  │              │  AULA L-509   │ AULA L-509 │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │ ING. DE SIS.│              │               │ALGO. Y PRO.│             │            │             │");
        System.out.println("│11:20-12:10│   YULIANA   │              │               │  EDUARDO   │             │            │             │");
        System.out.println("│           │ AULA L-509  │              │               │ AULA L-501 │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │              │               │ALGO. Y PRO.│             │            │             │");
        System.out.println("│12:10-1:00 │             │              │               │  EDUARDO   │             │            │             │");
        System.out.println("│           │             │              │               │ AULA L-501 │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │              │   CALCULO 1   │            │             │            │             │");
        System.out.println("│01:00-1:50 │             │              │    FRANKLIN   │            │             │            │             │");
        System.out.println("│           │             │              │   AULA L-601  │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │              │   CALCULO 1   │            │             │            │             │");
        System.out.println("│01:50-2:40 │             │              │    FRANKLIN   │            │             │            │             │");
        System.out.println("│           │             │              │   AULA L-601  │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │              │   CALCULO 1   │            │             │            │             │");
        System.out.println("│02:40-3:30 │             │              │    FRANKLIN   │            │             │            │             │");
        System.out.println("│           │             │              │   AULA L-601  │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │              │               │            │             │            │             │");
        System.out.println("│03:30-4:20 │             │              │               │            │             │            │             │");
        System.out.println("│           │             │              │               │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │              │               │            │             │            │             │");
        System.out.println("│04:20-5:10 │             │              │               │            │             │            │             │");
        System.out.println("│           │             │              │               │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │              │               │            │             │            │             │");
        System.out.println("│05:10-6:00 │             │              │               │            │             │            │             │");
        System.out.println("│           │             │              │               │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │              │               │            │             │            │             │");
        System.out.println("│06:00-6:50 │             │              │               │            │             │            │             │");
        System.out.println("│           │             │              │               │            │             │            │             │"); 
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │MATE. DISCRE.│              │               │            │             │            │             │");
        System.out.println("│06:50-7:40 │    RAUL     │              │               │            │             │            │             │");
        System.out.println("│           │  AULA L-509 │              │               │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │MATE. DISCRE.│MATE. DISCRE. │               │            │             │            │             │");
        System.out.println("│07:40-8:30 │    RAUL     │     RAUL     │               │            │             │            │             │");
        System.out.println("│           │  AULA L-509 │  AULA L-509  │               │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │MATE. DISCRE. │               │            │             │            │             │");
        System.out.println("│08:30-9:20 │             │     RAUL     │               │            │             │            │             │");
        System.out.println("│           │             │  AULA L-509  │               │            │             │            │             │");
        System.out.println("├───────────┼─────────────┼──────────────┼───────────────┼────────────┼─────────────┼────────────┼─────────────┤");
        System.out.println("│           │             │MATE. DISCRE. │               │            │             │            │             │");
        System.out.println("│09:20-10:10│             │     RAUL     │               │            │             │            │             │");
        System.out.println("│           │             │  AULA L-509  │               │            │             │            │             │");
        System.out.println("└───────────┴─────────────┴──────────────┴───────────────┴────────────┴─────────────┴────────────┴─────────────┘");
    }

    
}
